name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd people-dashboard
        npm ci
        
    - name: Build Electron app
      run: |
        cd people-dashboard
        npm run build
        npm run electron:build
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.os }}
        path: people-dashboard/dist/downloads/*
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build-*/People Dashboard*
        body: |
          ## 🚀 Release Notes
          
          Versione automatica build da GitHub Actions.
          
          ### 📦 Download
          - **Windows**: People Dashboard Setup.exe
          - **macOS**: People Dashboard.dmg  
          - **Linux**: People Dashboard.AppImage
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
