name: Build and Release

on:
  push:
    tags:
      - 'v*'

# Aggiunti permessi per creare release
permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Commentate temporaneamente le altre piattaforme - focus su Windows
        os: [windows-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      working-directory: people-dashboard
      run: npm ci
        
    - name: Build Electron app
      working-directory: people-dashboard
      run: |
        npm run build
        npm run electron:dist
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: people-dashboard/dist/downloads/*
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: List downloaded files (debug)
      run: |
        echo "=== Current directory ==="
        pwd
        echo "=== All files ==="
        find . -type f -name "*.exe" -o -name "*.msi" -o -name "*.zip" || echo "No build files found"
        ls -la || echo "No files in directory"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/*.exe
          **/*.msi
          **/*.zip
        body: |
          ## 🚀 Team Dashboard Release
          
          Build automatico da GitHub Actions per Windows.
          
          ### 📦 Download
          - **Windows**: Eseguibile per Windows
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
